default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123456
  host: localhost

development:
  <<: *default
  database: blog-system_development
  port: 5432
  host: localhost

test:
  <<: *default
  database: blog-system_test

production:
  <<: *default
  database: blog-system_production
  username: blog-system
  password: <%= ENV['BLOG-SYSTEM_DATABASE_PASSWORD'] %>
