default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog-system_development
  port: 5432
  pool: 5
  username: postgres
  password: postgres
  schema_search_path: public
  host: localhost

test:
  <<: *default
  database: blog-system_test

production:
  <<: *default
  database: blog-system_production
  username: blog-system
  password: <%= ENV['BLOG-SYSTEM_DATABASE_PASSWORD'] %>
